### ISSUE TITLE
I want to remove some modules from the `mage2pro/core` package

### ISSUE THREAD

**Issue by erikhansen** [mage2pro/backend-login-autocomplete#1]
Installing this extension via Composer downloads the `mage2pro/core` extension which is a bundled extension which contains a large number of other extensions:

```
Df_Core
Df_Backend
Df_Catalog
Df_Config
Df_API2
Df_Customer
Df_Directory
Df_Eav
Df_Framework
Df_Oauth
Df_Payment
Df_PaypalClone
Df_Qa
Df_Quote
Df_Sales
Df_Sentry
Df_Sso
Df_Store
Df_StripeClone
Df_Theme
Df_Typography
Df_User
Df_Xml
Df_Zf
```

Having all of these extensions installed on a site, just to enable this simple functionality, is an unacceptable level of bloat in my opinion. Can you pair down these dependencies?

**Comment by dmitrii-fediuk** [comment]
No.
